In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [0]:
df=pd.read_csv('housingdata.csv')

In [8]:
df.head()

0.00632   18  2.31  0  0.538  6.575  ...  1  296  15.3   396.9  4.98    24
0  0.02731  0.0  7.07  0  0.469  6.421  ...  2  242  17.8  396.90  9.14  21.6
1  0.02729  0.0  7.07  0  0.469  7.185  ...  2  242  17.8  392.83  4.03  34.7
2  0.03237  0.0  2.18  0  0.458  6.998  ...  3  222  18.7  394.63  2.94  33.4
3  0.06905  0.0  2.18  0  0.458  7.147  ...  3  222  18.7  396.90  5.33  36.2
4  0.02985  0.0  2.18  0  0.458  6.430  ...  3  222  18.7  394.12  5.21  28.7

[5 rows x 14 columns]

In [0]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [52]:
X

array([[2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       [3.2370e-02, 0.0000e+00, 2.1800e+00, ..., 1.8700e+01, 3.9463e+02,
        2.9400e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [53]:
y

array([21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. , 18.9,
       21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6, 15.2,
       14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2, 13.1,
       13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7, 21.2,
       19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9, 35.4,
       24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5, 19.4,
       22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. , 20.8,
       21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2, 23.6,
       28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8, 33.2,
       27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4, 21.7,
       22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. , 20.3,
       20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6, 23. ,
       18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4, 15.6,
       11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21.5, 19

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [0]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense




In [0]:
# Initialising the ANN
regressor = Sequential()

# Adding the input layer and the first hidden layer
regressor.add(Dense(units = 7, kernel_initializer = 'normal', activation = 'relu', input_dim = 13))

# Adding the second hidden layer
regressor.add(Dense(units = 6, kernel_initializer = 'normal', activation = 'relu'))

# Adding the output layer
regressor.add(Dense(units = 1, kernel_initializer = 'normal', activation = 'linear'))

# Compiling the ANN
regressor.compile(optimizer = 'adam', loss = 'mean_squared_error', metrics = ['mean_squared_error'])



In [65]:
# Fitting the ANN to the Training set
regressor.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
404/404 [==============================] - 1s 1ms/step - loss: 599.3132 - mean_squared_error: 599.3132
Epoch 2/100
404/404 [==============================] - 0s 161us/step - loss: 593.8611 - mean_squared_error: 593.8611
Epoch 3/100
404/404 [==============================] - 0s 134us/step - loss: 575.5812 - mean_squared_error: 575.5812
Epoch 4/100
404/404 [==============================] - 0s 159us/step - loss: 529.2437 - mean_squared_error: 529.2437
Epoch 5/100
404/404 [==============================] - 0s 125us/step - loss: 446.8811 - mean_squared_error: 446.8811
Epoch 6/100
404/404 [==============================] - 0s 130us/step - loss: 333.7462 - mean_squared_error: 333.7462
Epoch 7/100
404/404 [==============================] - 0s 129us/step - loss: 221.3514 - mean_squared_error: 221.3514
Epoch 8/100
404/404 [==============================] - 0s 161us/step - loss: 138.6615 - mean_squared_error: 138.6615
Epoch 9/100
404/404 [==============================] - 0s 116us/st

In [66]:
y_pred = regressor.predict(X_test)
y_pred 

array([[27.559942 ],
       [42.952168 ],
       [16.785646 ],
       [34.148933 ],
       [16.867895 ],
       [18.821272 ],
       [19.60412  ],
       [ 8.819736 ],
       [34.887367 ],
       [23.636135 ],
       [ 9.609602 ],
       [23.48074  ],
       [23.522255 ],
       [32.58982  ],
       [19.471167 ],
       [33.367462 ],
       [17.065485 ],
       [45.36424  ],
       [21.541777 ],
       [21.771572 ],
       [12.72978  ],
       [12.273127 ],
       [18.414272 ],
       [17.941889 ],
       [21.962242 ],
       [ 7.791077 ],
       [15.960435 ],
       [11.288469 ],
       [43.010723 ],
       [34.132137 ],
       [13.3001995],
       [17.985579 ],
       [22.551353 ],
       [22.211939 ],
       [22.989752 ],
       [28.234121 ],
       [24.745047 ],
       [14.142331 ],
       [19.344501 ],
       [33.62846  ],
       [24.205484 ],
       [20.669573 ],
       [13.107282 ],
       [47.431515 ],
       [22.829018 ],
       [34.066612 ],
       [11.410512 ],
       [19.65

In [67]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test,y_pred)

12.483063356248831

In [68]:
from sklearn.metrics import r2_score
r2_score(y_pred,y_test)


0.8460203461877995